In [2]:
print('START')

START

In [3]:
!pip install ibm_db

Collecting ibm_db
  Downloading https://files.pythonhosted.org/packages/6f/4e/48bf113d4f14b20a5008ea9f7784654041d8f7730c1081b370f569d80c93/ibm_db-3.0.2.tar.gz (718kB)
    100% |████████████████████████████████| 727kB 14.3MB/s ta 0:00:01
Building wheels for collected packages: ibm-db
  Running setup.py bdist_wheel for ibm-db ... done
  Stored in directory: /home/jovyan/.cache/pip/wheels/84/64/42/10b217b545e8085b72160632c61bfa0909f661dad89326a956
Successfully built ibm-db
Installing collected packages: ibm-db
Successfully installed ibm-db-3.0.2

In [4]:
import ibm_db

In [9]:
#Enter the values for you database connection

dsn_driver = "IBM DB2 ODBC DRIVER"
dsn_database = ""            # e.g. "BLUDB"
dsn_hostname = "" # e.g.: "awh-yp-small03.services.dal.bluemix.net"
dsn_port = ""                # e.g. "50000" 
dsn_protocol = "TCPIP"            # i.e. "TCPIP"
dsn_uid = ""        # e.g. "dash104434"
dsn_pwd = ""       # e.g. "7dBZ3jWt9xN6$o0JiX!m"

In [12]:
dsn = (
    "DRIVER={{IBM DB2 ODBC DRIVER}};"
    "DATABASE={0};"
    "HOSTNAME={1};"
    "PORT={2};"
    "PROTOCOL=TCPIP;"
    "UID={3};"
    "PWD={4};"
    "Security={5};").format(dsn_database, dsn_hostname, dsn_port, dsn_uid, dsn_pwd,"SSL")

conn = ibm_db.connect(dsn, "", "")

In [17]:
# test query
query = "SELECT count(*) FROM DB2INST1.SENSORDATA ;"
# run direct SQL
stmt = ibm_db.exec_immediate(conn, query)
ibm_db.fetch_both(stmt)

{'1': '2177', 0: '2177'}

In [41]:
import pandas
import ibm_db_dbi
pconn = ibm_db_dbi.Connection(conn)
df = pandas.read_sql('SELECT * FROM DB2INST1.SENSORDATA WHERE "Humidity" > 90 LIMIT 10', pconn)
df

,Date,Time,DateTime,Sensor,Location,Temperature,Humidity,Pressure,Comment,TIMESTAMP,...,LORAPAY,DEVEUI,APPNAME,VOLTAGE,FRAMECNT,FREQUENCY,LATITUDE,LONGITUDE,ALTITUDE,GATEWAYID
0,2020-02-25,10:00:00,2020-10-21 16:30,TTGO,LocationLocation,24.11,1000.12,1000.12,wwwwwwwwwwwwqqqldsflsdjfhsdhfhsdhfwwwwwwwwwwww...,None,...,None,None,None,NaN,None,None,NaN,None,None,None
1,2020-02-25,10:01:00,2020-10-21 16:30,PYCOM,Markus SNP,-10.51,1000.12,1000.12,Markus SNPMarkus SNPMarkus SNPMarkus SNPMarkus...,None,...,None,None,None,NaN,None,None,NaN,None,None,None
2,None,None,None,ttgo,None,19.70,90.50,NaN,None,None,...,AYgAAAAAAAAAAAABdAGVAXXoSAEAAAECJw8BAZcBZwDFAW...,70b3d57ed0035849,ttgotest,4.0,None,None,43.0,None,None,None
3,None,None,None,ttgo,None,19.20,96.50,NaN,None,None,...,AYgAAAAAAAAAAAABdAGUAXXYqAEAAAECJw8BAZgBZwDAAW...,70b3d57ed0035849,ttgotest,4.0,None,None,43.0,None,None,None
4,None,None,None,ttgo,None,18.70,100.00,NaN,None,None,...,AYgAAAAAAAAAAAABdAGUAXW7XAEAAAECJw8BAZkBZwC7AW...,70b3d57ed0035849,ttgotest,4.0,None,None,43.0,None,None,None
5,None,None,None,ttgo,None,18.40,100.00,NaN,None,None,...,AYgAAAAAAAAAAAABdAGUAXXehAEAAAECJw8BAZoBZwC4AW...,70b3d57ed0035849,ttgotest,4.0,None,None,43.0,None,None,None
6,None,None,None,ttgo,None,18.00,100.00,NaN,None,None,...,AYgAAAAAAAAAAAABdAGUAXWn1AEAAAECJw8BAZsBZwC0AW...,70b3d57ed0035849,ttgotest,4.0,None,None,43.0,None,None,None
7,None,None,None,ttgo,None,17.90,100.00,NaN,None,None,...,AYgAAAAAAAAAAAABdAGUAXXQ2AEAAAECJw8BAZwBZwCzAW...,70b3d57ed0035849,ttgotest,4.0,None,None,43.0,None,None,None
8,None,None,None,ttgo,None,18.10,100.00,NaN,None,None,...,AYgAAAAAAAAAAAABdAGUAXXQ2AEAAAECJw8BAZ0BZwC1AW...,70b3d57ed0035849,ttgotest,4.0,None,None,43.0,None,None,None
9,None,None,None,ttgo,None,18.80,100.00,NaN,None,None,...,AYgGqdXz4h8AMlkBdAGTAXWcHAEAAwECAVoBAZ4BZwC8AW...,70b3d57ed0035849,ttgotest,4.0,None,None,43.0,None,None,None

In [48]:
import pandas
import ibm_db_dbi
pconn = ibm_db_dbi.Connection(conn)
df = pandas.read_sql("SELECT * FROM DB2INST1.SENSORDATA  LIMIT 10;", pconn)
df

,Date,Time,DateTime,Sensor,Location,Temperature,Humidity,Pressure,Comment,TIMESTAMP,...,LORAPAY,DEVEUI,APPNAME,VOLTAGE,FRAMECNT,FREQUENCY,LATITUDE,LONGITUDE,ALTITUDE,GATEWAYID
0,None,None,None,ttgo,None,8.7,65.0,None,None,None,...,AYgGqdTz4iQAOYABdAF5AXWOcAEACQECAGQBAV8BZwBXAW...,70b3d57ed0035849,ttgotest,3,None,None,43.0,None,None,None
1,None,None,None,ttgo,None,8.7,64.5,None,None,None,...,AYgGqdTz4iQAObIBdAF5AXWSWAEACQECAGkBAWEBZwBXAW...,70b3d57ed0035849,ttgotest,3,None,None,43.0,None,None,None
2,None,None,None,ttgo,None,8.7,64.5,None,None,None,...,AYgGqdTz4iYAQAYBdAF4AXWOcAEACQECAGgBAWIBZwBXAW...,70b3d57ed0035849,ttgotest,3,None,None,43.0,None,None,None
3,None,None,None,ttgo,None,8.7,64.0,None,None,None,...,AYgGqdTz4igAQuABdAF4AXWQZAEACQECAHABAWQBZwBXAW...,70b3d57ed0035849,ttgotest,3,None,None,43.0,None,None,None
4,None,None,None,ttgo,None,8.7,64.0,None,None,None,...,AYgGqdTz4iUAPOUBdAF4AXWcHAEACQECAGQBAWUBZwBXAW...,70b3d57ed0035849,ttgotest,3,None,None,43.0,None,None,None
5,None,None,None,ttgo,None,8.6,64.0,None,None,None,...,AYgGqdTz4iQAOQgBdAF4AXWGoAEACAECAGgBAWcBZwBWAW...,70b3d57ed0035849,ttgotest,3,None,None,43.0,None,None,None
6,None,None,None,ttgo,None,8.5,64.0,None,None,None,...,AYgGqdTz4iMANuwBdAF4AXWErAEACQECAGMBAWgBZwBVAW...,70b3d57ed0035849,ttgotest,3,None,None,43.0,None,None,None
7,None,None,None,ttgo,None,8.5,64.0,None,None,None,...,AYgGqdTz4iMANwABdAF4AXWGoAEACQECAGMBAWkBZwBVAW...,70b3d57ed0035849,ttgotest,3,None,None,43.0,None,None,None
8,None,None,None,ttgo,None,8.4,64.0,None,None,None,...,AYgGqdTz4iUAODUBdAF4AXWgBAEACQECAGMBAWoBZwBUAW...,70b3d57ed0035849,ttgotest,3,None,None,43.0,None,None,None
9,None,None,None,ttgo,None,8.4,64.5,None,None,None,...,AYgGqdTz4iUAOkgBdAF4AXWaKAEACAECAHwBAWwBZwBUAW...,70b3d57ed0035849,ttgotest,3,None,None,43.0,None,None,None

In [64]:
query = ("SELECT * FROM DB2INST1.SENSORDATA  WHERE 'Temperature' > '10'")
query = ('SELECT * FROM DB2INST1.SENSORDATA WHERE "Humidity" > 90 LIMIT 10')
query = ('SELECT * FROM DB2INST1.SENSORDATA WHERE "Temperature" >10 LIMIT 10')
result = pandas.read_sql(query,pconn)
result

,Date,Time,DateTime,Sensor,Location,Temperature,Humidity,Pressure,Comment,TIMESTAMP,...,LORAPAY,DEVEUI,APPNAME,VOLTAGE,FRAMECNT,FREQUENCY,LATITUDE,LONGITUDE,ALTITUDE,GATEWAYID
0,2020-02-25,10:00:00,2020-10-21 16:30,TTGO,LocationLocation,24.11,1000.12,1000.12,wwwwwwwwwwwwqqqldsflsdjfhsdhfhsdhfwwwwwwwwwwww...,None,...,None,None,None,NaN,None,None,NaN,None,None,None
1,None,None,None,ttgo,None,17.90,28.50,NaN,None,None,...,AYgGqdTz4iQANnMBdAE0AXXK/AEABQECAJkBAQABZwCzAW...,70b3d57ed0035849,ttgotest,3.0,None,None,43.0,None,None,None
2,None,None,None,ttgo,None,18.20,28.50,NaN,None,None,...,AYgGqdTz4iMAN1oBdAEsAXXFIAEABQECAJgBAQEBZwC2AW...,70b3d57ed0035849,ttgotest,3.0,None,None,43.0,None,None,None
3,None,None,None,ttgo,None,27.00,NaN,NaN,None,None,...,AYgAAAAAAAAAAAABdAGjAXUAAAEAAAECJw8BAQcBZwEOAW...,70b3d57ed0035849,ttgotest,NaN,None,None,NaN,None,None,None
4,None,None,None,ttgo,None,26.80,NaN,NaN,None,None,...,AYgAAAAAAAAAAAABdAGjAXUAAAEAAAECJw8BAQwBZwEMAW...,70b3d57ed0035849,ttgotest,NaN,None,None,NaN,None,None,None
5,None,None,None,ttgo,None,26.40,33.00,NaN,None,None,...,AYgAAAAAAAAAAAABdAGjAXUAAAEAAAECJw8BARcBZwEIAW...,70b3d57ed0035849,ttgotest,4.0,None,None,NaN,None,None,None
6,None,None,None,ttgo,None,25.90,34.00,NaN,None,None,...,AYgAAAAAAAAAAAABdAGgAXUAAAEAAAECJw8BASwBZwEDAW...,70b3d57ed0035849,ttgotest,4.0,None,None,NaN,None,None,None
7,None,None,None,ttgo,None,25.80,34.00,NaN,None,None,...,AYgAAAAAAAAAAAABdAGfAXUAAAEAAAECJw8BAS0BZwECAW...,70b3d57ed0035849,ttgotest,4.0,None,None,43.0,None,None,None
8,None,None,None,ttgo,None,25.10,36.00,NaN,None,None,...,AYgAAAAAAAAAAAABdAGaAXUAAAEAAAECJw8BAVsBZwD7AW...,70b3d57ed0035849,ttgotest,4.0,None,None,43.0,None,None,None
9,None,None,None,ttgo,None,25.10,36.00,NaN,None,None,...,AYgAAAAAAAAAAAABdAGaAXUAAAEAAAECJw8BAVwBZwD7AW...,70b3d57ed0035849,ttgotest,4.0,None,None,43.0,None,None,None